# Generated by Django 5.2.1 on 2025-05-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='Ubicacion no asignada', max_length=100),
        ),
    ]
