# Generated by Django 5.2.1 on 2025-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin categoria', max_length=100),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
