# Generated by Django 5.1.4 on 2025-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(default='Fabricante Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='Modelo Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='n_serie',
            field=models.IntegerField(default=0),
        ),
    ]
