# Generated by Django 5.2.1 on 2025-06-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_fabricante_producto_modelo_producto_n_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
