# Generated by Django 5.1.4 on 2025-06-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('creación', 'Creación'), ('edición', 'Edición'), ('eliminación', 'Eliminación')], max_length=20),
        ),
    ]
