# Generated by Django 5.1.4 on 2025-06-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_proyecto_movimiento_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
